on: push

name: Test and build

jobs:
  build-linux:
    name: build-linux
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt install gcc libc6-dev
          sudo apt install libx11-dev xorg-dev libxtst-dev libpng++-dev
          sudo apt install xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev
          sudo apt install libxkbcommon-dev
          sudo apt install xsel xclip

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: |
          go build -o amk-linux-amd64
          chmod a+x ./amk-linux-amd64
          tar -czvf amk-linux-amd64.tar.gz ./amk-linux-amd64
          ls -al
          mkdir release
          mv amk-linux-amd64.tar.gz release

      - name: Test
        run: go test -v ./...

  build-windows:
    name: build-windows
    runs-on: windows-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: |
          go build -o amk-windows.exe
          ls
          mkdir release
          mv amk-windows.exe release

      - name: Test
        run: go test -v ./...

  build-macos:
    name: build-macOS
    runs-on: macOS-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: |
          go build -o amk-macos
          mkdir release
          mv amk-macos release

      - name: Test
        run: go test -v ./...